//---------------------------------------------------------------------------

#ifndef DFormH
#define DFormH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Menus.hpp>
#include <ComCtrls.hpp>
#include <ToolWin.hpp>
#include <Buttons.hpp>
#include <Grids.hpp>
#include <Dialogs.hpp>
#include <ImgList.hpp>
#include <Graphics.hpp>

#define REG_EMPTY 0x3c96bad3


//---------------------------------------------------------------------------
class TMainForm : public TForm
{
__published:	// IDE-managed Components
        TSplitter *Splitter1;
        TMainMenu *MainMenu1;
        TMenuItem *File1;
        TCoolBar *CoolBar1;
        TPanel *EditorPanel;
        TPanel *Panel3;
        TComboBox *cbComPort;
        TPanel *Panel4;
        TSpeedButton *bCompLoad;
        TSpeedButton *bConnect;
        TStatusBar *SBar;
        TSplitter *Splitter2;
        TSpeedButton *bRun;
        TMenuItem *New1;
        TMenuItem *Open1;
        TMenuItem *Save1;
        TMenuItem *SaveAs1;
        TMenuItem *N1;
        TMenuItem *Exit1;
        TMenuItem *N2;
        TMenuItem *Edit1;
        TSpeedButton *bDisconnect;
        TOpenDialog *NewFileDlg;
        TSaveDialog *SaveAsDlg;
        TPopupMenu *AsmTextPopup;
        TMenuItem *AtCut;
        TMenuItem *AtCopy;
        TMenuItem *AtPaste;
        TMenuItem *N3;
        TMenuItem *AtCompile;
        TMenuItem *AtLoadto;
        TMenuItem *AtRun;
        TTimer *ConTracker;
        TPanel *Indy;
        TTimer *LineUpdateTimer;
        TPopupMenu *DumpMenu;
        TMenuItem *Followaddress1;
        TMenuItem *Followaddressinotherwin1;
        TMenuItem *Goto1;
        TMenuItem *Back1;
        TMenuItem *Search1;
        TMenuItem *Loadfromfile1;
        TMenuItem *Savetofile1;
        TMenuItem *View1;
        TMenuItem *Debug1;
        TMenuItem *Tools1;
        TMenuItem *Help1;
        TMenuItem *Opensession1;
        TMenuItem *Savesession1;
        TMenuItem *Savesessionas1;
        TMenuItem *CPUwindow1;
        TMenuItem *Memorymap1;
        TMenuItem *Breakpoints1;
        TMenuItem *Log1;
        TMenuItem *CP15registers1;
        TMenuItem *About1;
        TMenuItem *Names1;
        TMenuItem *N5;
        TMenuItem *Refresh1;
        TMenuItem *HexASCII1;
        TPanel *Panel5;
        TSplitter *Splitter3;
        TDrawGrid *Dump1;
        TPanel *Panel6;
        TMenuItem *SearchAgain1;
        TPopupMenu *LogPopup;
        TMenuItem *Clear1;
        TMenuItem *Savetofile2;
        TSpeedButton *bBoot;
        TDrawGrid *Registers;
        TMenuItem *N6;
        TMenuItem *Find1;
        TMenuItem *FindAgain1;
        TMenuItem *SelectAll1;
        TPanel *SearchPanel;
        TSpeedButton *bSearchType;
        TComboBox *eHexSearch;
        TMenuItem *Close1;
        TPopupMenu *PagesPopup;
        TMenuItem *Newfile1;
        TMenuItem *openFile1;
        TMenuItem *ClosePage1;
        TMenuItem *Calladdress1;
        TMenuItem *Patchmemory1;
        TMenuItem *ApplyVKP1;
        TOpenDialog *OpenVkpDlg;
        TMenuItem *References1;
        TMenuItem *Patches1;
        TOpenDialog *OpenSessionDlg;
        TMenuItem *Sessionoptions1;
        TMenuItem *Newsession1;
        TMenuItem *Compileroutput1;
        TMenuItem *Breakpointonwrite1;
        TPopupMenu *CPUPopup;
        TMenuItem *Follow1;
        TMenuItem *Assemble12;
        TMenuItem *ARMThumb1;
        TMenuItem *Back2;
        TMenuItem *Refresh2;
        TMenuItem *Goto2;
        TMenuItem *References2;
        TMenuItem *Copy1;
        TMenuItem *Paste1;
        TTimer *MonitorTimer;
        TMenuItem *Monitor1;
        TMenuItem *Patch12;
        TMenuItem *Fill1;
        TStaticText *MonSticker1;
        TPanel *Panel7;
        TDrawGrid *Dump2;
        TStaticText *MonSticker2;
        TMenuItem *RAMAccessAnalyzer1;
        TMenuItem *GenerateCGSNpatch1;
        TMenuItem *N8;
        TPanel *Panel1;
        TPageControl *Pages;
        TTabSheet *Sheet1;
        TTabSheet *Sheet2;
        TTabSheet *Sheet3;
        TTabSheet *Sheet4;
        TTabSheet *Sheet5;
        TLabel *Label1;
        TTabSheet *Sheet6;
        TTabSheet *Sheet7;
        TTabSheet *Sheet8;
        TTabSheet *Sheet9;
        TTabSheet *SheetCPU;
        TStaticText *StaticText1;
        TMenuItem *switchtodump11;
        TMenuItem *switchtodump12;
        TMenuItem *switchtolog1;
        TMenuItem *switchtolog2;
        TMenuItem *switchtoeditor1;
        TMenuItem *switchtoDump21;
        TMenuItem *altup1;
        TMenuItem *Undopatch1;
        TOpenDialog *OpenBinDlg;
        TMenuItem *SetLoadTarger1;
        TMenuItem *Name1;
        TMenuItem *LoadNames1;
        TMenuItem *ExportNames1;
        TMenuItem *Savememorytofile1;
        TOpenDialog *ImportIdcDlg;
        TSaveDialog *ExportIdcDlg;
        TPopupMenu *SideNamesPopup;
        TMenuItem *SortbyAddress1;
        TMenuItem *SortbyName1;
        TBevel *Bevel1;
        TPanel *Panel2;
        TMenuItem *switchtovCPU1;
        TMenuItem *switchtolog3;
        TMenuItem *switchto1;
        TMenuItem *switchtosidenames1;
        TMenuItem *armthumb2;
        TPanel *Panel8;
        TSpeedButton *SpeedButton1;
        TSpeedButton *SpeedButton2;
        TSpeedButton *SpeedButton3;
        TSaveDialog *SaveSessionAsDlg;
        TPanel *Panel9;
        TSpeedButton *bCPU;
        TSpeedButton *bNames;
        TSpeedButton *bPatches;
        TMenuItem *RemoveLoadTarget1;
        TMenuItem *Rename1;
        TMenuItem *Undefine1;
        TMenuItem *N9;
        TMenuItem *Atomicassemble1;
        TMenuItem *CpuEdit1;
        TMenuItem *Copy2;
        TMenuItem *Paste2;
        TMenuItem *Calculator1;
        TMenuItem *N10;
        TMenuItem *Crossreferences1;
        TMenuItem *N4;
        TMenuItem *N11;
        TMenuItem *Bookmarks1;
        TMenuItem *Bookmark1;
        TMenuItem *Bookmark2;
        TSpeedButton *bSnaps;
        TPopupMenu *SearchPopup;
        TMenuItem *Cut1;
        TMenuItem *Copy3;
        TMenuItem *Paste3;
        TMenuItem *N12;
        TMenuItem *Bookmark3;
        TMenuItem *SetSnappoint1;
        TPanel *Panel10;
        TRichEdit *LogWindow;
        TMemo *Mes;
        TMenuItem *Deviceinformation1;
        TSpeedButton *SpeedButton9;
        TTimer *EventTimer;
        TMenuItem *N13;
        TMenuItem *Removewatchpoint1;
        TMenuItem *FollowaddressinCPUwindow1;
        TMenuItem *Follow2;
        TMenuItem *Watchpoint2;
        TMenuItem *Gotowatchpoint1;
        TMenuItem *DebugSubmenu;
        TMenuItem *Fastsnappoint1;
        TDrawGrid *WatchesList;
        TPopupMenu *WatchesPopup;
        TMenuItem *Newwatch1;
        TMenuItem *ChangeWatch1;
        TMenuItem *Delete1;
        TMenuItem *MenuItem1;
        TMenuItem *MenuItem2;
        TMenuItem *MenuItem3;
        TMenuItem *MenuItem4;
        TMenuItem *MenuItem5;
        TMenuItem *MenuItem6;
        TStaticText *MonStickerW;
        TMenuItem *switchtoregisters1;
        TPopupMenu *RegistersPopup;
        TMenuItem *ViewItem1;
        TMenuItem *switchtolog4;
        TMenuItem *switchtodump1;
        TMenuItem *switchtowatches1;
        TMenuItem *switchtoregisters2;
        TMenuItem *switchtodump2;
        TPopupMenu *MesPopup;
        TMenuItem *Copy4;
        TMenuItem *switchtoasm1;
        TMenuItem *switchtoregisters3;
        TMenuItem *Copy5;
        TMenuItem *Bookmark4;
        TMenuItem *File2;
        TSpeedButton *bSearch;
        TMenuItem *OpeninDumpwindow1;
        TMenuItem *OpeninCPUwindow1;
        TSpeedButton *bOff;
        TTimer *AdrTimer;
        TMenuItem *CopyAddress1;
        TMenuItem *CopyWord1;
        TMenuItem *Enablepatch1;
        TMenuItem *DisablePatch1;
        TMenuItem *EnableAllPatches1;
        TMenuItem *DisableAllPatches1;
        TMenuItem *FlashMapViewer1;
        TMenuItem *NucleusRTOSresources1;
        TMenuItem *SetBreakpoint1;
        TMenuItem *Run1;
        TMenuItem *StepInto1;
        TMenuItem *StepOver1;
        TMenuItem *SetBreakpoint2;
        TMenuItem *SetFastSnappoint2;
        TMenuItem *SetSnappoint2;
        TMenuItem *N7;
        TMenuItem *N14;
        TMenuItem *ProgramReset1;
        TSpeedButton *bStepInto;
        TSpeedButton *bStepOver;
        TRichEdit *AsmText1;
        TRichEdit *AsmText2;
        TRichEdit *AsmText3;
        TRichEdit *AsmText4;
        TRichEdit *AsmText5;
        TRichEdit *AsmText6;
        TRichEdit *AsmText7;
        TRichEdit *AsmText8;
        TRichEdit *AsmText9;
        TPopupMenu *CPUPopup2;
        TMenuItem *Name2;
        TMenuItem *CopyBinary1;
        TMenuItem *FollowinCPUWindow1;
        TMenuItem *RegistersEdit2;
        TMenuItem *switchtodump13;
        TMenuItem *switchtolog5;
        TMenuItem *switchtosidenames2;
        TImageList *Icons;
        TMenuItem *N15;
        TMenuItem *NewOriginHere1;
        TMenuItem *GotoOrigin1;
        TMenuItem *Trace1;
        TSplitter *Splitter4;
        TDrawGrid *vCPU;
        TPanel *Panel11;
        TListBox *SideNames;
        TSpeedButton *SpeedButton4;
        TSplitter *Splitter5;
        TSpeedButton *bSearchTab;
        TMenuItem *Breakpoints2;
        TMenuItem *Terminal1;
        TSpeedButton *bVkp;
        TMenuItem *Memorizeaspatch1;
        void __fastcall bCompLoadClick(TObject *Sender);
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall cbComPortChange(TObject *Sender);
        void __fastcall bDisconnectClick(TObject *Sender);
        void __fastcall bConnectClick(TObject *Sender);
        void __fastcall New1Click(TObject *Sender);
        void __fastcall AsmTextChange(TObject *Sender);
        void __fastcall Open1Click(TObject *Sender);
        void __fastcall Save1Click(TObject *Sender);
        void __fastcall SaveAs1Click(TObject *Sender);
        void __fastcall AtCutClick(TObject *Sender);
        void __fastcall AtCopyClick(TObject *Sender);
        void __fastcall AtPasteClick(TObject *Sender);
        void __fastcall AtLoadtoClick(TObject *Sender);
        void __fastcall AtRunClick(TObject *Sender);
        void __fastcall ConTrackerTimer(TObject *Sender);
        void __fastcall PagesChange(TObject *Sender);
        void __fastcall bRunClick(TObject *Sender);
        void __fastcall AsmText1MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall AsmText1KeyDown(TObject *Sender, WORD &Key,
          TShiftState Shift);
        void __fastcall LineUpdateTimerTimer(TObject *Sender);
        void __fastcall Savememorytofile1Click(TObject *Sender);
        void __fastcall Dump1Enter(TObject *Sender);
        void __fastcall Dump1TopLeftChanged(TObject *Sender);
        void __fastcall Dump1DrawCell(TObject *Sender, int ACol, int ARow,
          TRect &Rect, TGridDrawState State);
        void __fastcall Dump2DrawCell(TObject *Sender, int ACol, int ARow,
          TRect &Rect, TGridDrawState State);
        void __fastcall About1Click(TObject *Sender);
        void __fastcall Dump2Enter(TObject *Sender);
        void __fastcall Dump2TopLeftChanged(TObject *Sender);
        void __fastcall FormCloseQuery(TObject *Sender, bool &CanClose);
        void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall Refresh1Click(TObject *Sender);
        void __fastcall Dump12KeyPress(TObject *Sender, char &Key);
        void __fastcall Goto1Click(TObject *Sender);
        void __fastcall Dump2Exit(TObject *Sender);
        void __fastcall Back1Click(TObject *Sender);
        void __fastcall Followaddress1Click(TObject *Sender);
        void __fastcall Followaddressinotherwin1Click(TObject *Sender);
        void __fastcall Dump12DblClick(TObject *Sender);
        void __fastcall HexASCII1Click(TObject *Sender);
        void __fastcall Savetofile1Click(TObject *Sender);
        void __fastcall Dump12Click(TObject *Sender);
        void __fastcall bBootClick(TObject *Sender);
        void __fastcall SelectAll1Click(TObject *Sender);
        void __fastcall Find1Click(TObject *Sender);
        void __fastcall MesDblClick(TObject *Sender);
        void __fastcall FindAgain1Click(TObject *Sender);
        void __fastcall bSearchTypeClick(TObject *Sender);
        void __fastcall eHexSearchKeyPress(TObject *Sender, char &Key);
        void __fastcall bSearchClick(TObject *Sender);
        void __fastcall Search1Click(TObject *Sender);
        void __fastcall SearchAgain1Click(TObject *Sender);
        void __fastcall RegistersDrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
        void __fastcall Panel5Resize(TObject *Sender);
        void __fastcall Splitter3Moved(TObject *Sender);
        void __fastcall Close1Click(TObject *Sender);
        void __fastcall Newfile1Click(TObject *Sender);
        void __fastcall openFile1Click(TObject *Sender);
        void __fastcall ClosePage1Click(TObject *Sender);
        void __fastcall Calladdress1Click(TObject *Sender);
        void __fastcall Patchmemory1Click(TObject *Sender);
        void __fastcall ApplyVKP1Click(TObject *Sender);
        void __fastcall Opensession1Click(TObject *Sender);
        void __fastcall Savesession1Click(TObject *Sender);
        void __fastcall Patches1Click(TObject *Sender);
        void __fastcall CPUwindow1Click(TObject *Sender);
        void __fastcall Dump12SelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
        void __fastcall Dump12MouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall Dump12MouseUp(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
        void __fastcall Copy1Click(TObject *Sender);
        void __fastcall Paste1Click(TObject *Sender);
        void __fastcall MonitorTimerTimer(TObject *Sender);
        void __fastcall Monitor1Click(TObject *Sender);
        void __fastcall DumpMenuPopup(TObject *Sender);
        void __fastcall Log1Click(TObject *Sender);
        void __fastcall Compileroutput1Click(TObject *Sender);
        void __fastcall Fill1Click(TObject *Sender);
        void __fastcall Exit1Click(TObject *Sender);
        void __fastcall CP15registers1Click(TObject *Sender);
        void __fastcall RAMAccessAnalyzer1Click(TObject *Sender);
        void __fastcall GenerateCGSNpatch1Click(TObject *Sender);
        void __fastcall vCPUDblClick(TObject *Sender);
        void __fastcall vCPUDrawCell(TObject *Sender, int ACol, int ARow,
          TRect &Rect, TGridDrawState State);
        void __fastcall vCPUMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
        void __fastcall vCPUMouseUp(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
        void __fastcall vCPUSelectCell(TObject *Sender, int ACol, int ARow,
          bool &CanSelect);
        void __fastcall vCPUTopLeftChanged(TObject *Sender);
        void __fastcall Refresh2Click(TObject *Sender);
        void __fastcall Follow1Click(TObject *Sender);
        void __fastcall Goto2Click(TObject *Sender);
        void __fastcall Back2Click(TObject *Sender);
        void __fastcall FormResize(TObject *Sender);
        void __fastcall switchtodump11Click(TObject *Sender);
        void __fastcall switchtolog1Click(TObject *Sender);
        void __fastcall switchtoeditor1Click(TObject *Sender);
        void __fastcall DumpAltDownClick(TObject *Sender);
        void __fastcall altup1Click(TObject *Sender);
        void __fastcall Undopatch1Click(TObject *Sender);
        void __fastcall Loadfromfile1Click(TObject *Sender);
        void __fastcall SetLoadTarger1Click(TObject *Sender);
        void __fastcall Name1Click(TObject *Sender);
        void __fastcall LoadNames1Click(TObject *Sender);
        void __fastcall ExportNames1Click(TObject *Sender);
        void __fastcall Assemble12Click(TObject *Sender);
        void __fastcall SaveAsDlgTypeChange(TObject *Sender);
        void __fastcall SortbyAddress1Click(TObject *Sender);
        void __fastcall SortbyName1Click(TObject *Sender);
        void __fastcall SideNamesDblClick(TObject *Sender);
        void __fastcall SideNamesKeyPress(TObject *Sender, char &Key);
        void __fastcall switchtovCPU1Click(TObject *Sender);
        void __fastcall switchtolog3Click(TObject *Sender);
        void __fastcall switchto1Click(TObject *Sender);
        void __fastcall switchtosidenames1Click(TObject *Sender);
        void __fastcall Names1Click(TObject *Sender);
        void __fastcall ARMThumb1Click(TObject *Sender);
        void __fastcall Sessionoptions1Click(TObject *Sender);
        void __fastcall SpeedButton1Click(TObject *Sender);
        void __fastcall SpeedButton2Click(TObject *Sender);
        void __fastcall SpeedButton3Click(TObject *Sender);
        void __fastcall Newsession1Click(TObject *Sender);
        void __fastcall Savesessionas1Click(TObject *Sender);
        void __fastcall AsmTextPopupPopup(TObject *Sender);
        void __fastcall RemoveLoadTarget1Click(TObject *Sender);
        void __fastcall Rename1Click(TObject *Sender);
        void __fastcall Undefine1Click(TObject *Sender);
        void __fastcall Memorymap1Click(TObject *Sender);
        void __fastcall Calculator1Click(TObject *Sender);
        void __fastcall References1Click(TObject *Sender);
        void __fastcall References2Click(TObject *Sender);
        void __fastcall Crossreferences1Click(TObject *Sender);
        void __fastcall Bookmarks1Click(TObject *Sender);
        void __fastcall SpeedButton9Click(TObject *Sender);
        void __fastcall Bookmark1Click(TObject *Sender);
        void __fastcall Bookmark2Click(TObject *Sender);
        void __fastcall Cut1Click(TObject *Sender);
        void __fastcall Copy3Click(TObject *Sender);
        void __fastcall Paste3Click(TObject *Sender);
        void __fastcall Bookmark3Click(TObject *Sender);
        void __fastcall Clear1Click(TObject *Sender);
        void __fastcall Deviceinformation1Click(TObject *Sender);
        void __fastcall SetSnappoint1Click(TObject *Sender);
        void __fastcall Breakpoints1Click(TObject *Sender);
        void __fastcall EventTimerTimer(TObject *Sender);
        void __fastcall Breakpointonwrite1Click(TObject *Sender);
        void __fastcall Removewatchpoint1Click(TObject *Sender);
        void __fastcall Newwatch1Click(TObject *Sender);
        void __fastcall ChangeWatch1Click(TObject *Sender);
        void __fastcall Delete1Click(TObject *Sender);
        void __fastcall MenuItem2Click(TObject *Sender);
        void __fastcall MenuItem3Click(TObject *Sender);
        void __fastcall MenuItem5Click(TObject *Sender);
        void __fastcall MenuItem6Click(TObject *Sender);
        void __fastcall WatchesListDrawCell(TObject *Sender, int ACol, int ARow,
          TRect &Rect, TGridDrawState State);
        void __fastcall switchtoregisters1Click(TObject *Sender);
        void __fastcall switchtolog4Click(TObject *Sender);
        void __fastcall switchtodump1Click(TObject *Sender);
        void __fastcall switchtowatches1Click(TObject *Sender);
        void __fastcall switchtoregisters2Click(TObject *Sender);
        void __fastcall switchtodump2Click(TObject *Sender);
        void __fastcall switchtoasm1Click(TObject *Sender);
        void __fastcall switchtoregisters3Click(TObject *Sender);
        void __fastcall Copy4Click(TObject *Sender);
        void __fastcall Copy5Click(TObject *Sender);
        void __fastcall FollowaddressinCPUwindow1Click(TObject *Sender);
        void __fastcall Gotowatchpoint1Click(TObject *Sender);
        void __fastcall Bookmark4Click(TObject *Sender);
        void __fastcall Fastsnappoint1Click(TObject *Sender);
        void __fastcall OpeninDumpwindow1Click(TObject *Sender);
        void __fastcall OpeninCPUwindow1Click(TObject *Sender);
        void __fastcall LogWindowMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall bOffClick(TObject *Sender);
        void __fastcall AdrTimerTimer(TObject *Sender);
        void __fastcall CopyAddress1Click(TObject *Sender);
        void __fastcall CopyWord1Click(TObject *Sender);
        void __fastcall Enablepatch1Click(TObject *Sender);
        void __fastcall DisablePatch1Click(TObject *Sender);
        void __fastcall EnableAllPatches1Click(TObject *Sender);
        void __fastcall DisableAllPatches1Click(TObject *Sender);
        void __fastcall FlashMapViewer1Click(TObject *Sender);
        void __fastcall NucleusRTOSresources1Click(TObject *Sender);
        void __fastcall SetBreakpoint1Click(TObject *Sender);
        void __fastcall ProgramReset1Click(TObject *Sender);
        void __fastcall bStepIntoClick(TObject *Sender);
        void __fastcall bStepOverClick(TObject *Sender);
        void __fastcall Copy2Click(TObject *Sender);
        void __fastcall CopyBinary1Click(TObject *Sender);
        void __fastcall Paste2Click(TObject *Sender);
        void __fastcall RegistersDblClick(TObject *Sender);
        void __fastcall ViewItem1Click(TObject *Sender);
        void __fastcall FollowinCPUWindow1Click(TObject *Sender);
        void __fastcall RegistersMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall RegistersSelectCell(TObject *Sender, int ACol,
          int ARow, bool &CanSelect);
        void __fastcall RegistersPopupPopup(TObject *Sender);
        void __fastcall RegistersEdit2Click(TObject *Sender);
        void __fastcall NewOriginHere1Click(TObject *Sender);
        void __fastcall GotoOrigin1Click(TObject *Sender);
        void __fastcall Trace1Click(TObject *Sender);
        void __fastcall cbComPortDropDown(TObject *Sender);
        void __fastcall bSearchTabClick(TObject *Sender);
        void __fastcall FormKeyPress(TObject *Sender, char &Key);
        void __fastcall Panel6Resize(TObject *Sender);
        void __fastcall Terminal1Click(TObject *Sender);
        void __fastcall bVkpClick(TObject *Sender);
        void __fastcall Memorizeaspatch1Click(TObject *Sender);
private:	// User declarations
public:		// User declarations

        __fastcall TMainForm(TComponent* Owner);

};
//---------------------------------------------------------------------------
extern PACKAGE TMainForm *MainForm;
//---------------------------------------------------------------------------

extern bool inprocess;

void openSource(char *name);
char *compile(char *filename, bool log);
char *compileAPC();
void execBinary(char *name, bool istrace);
void run(bool istrace);
void save();
void saveAs();
void loadToAddress(unsigned int a);
void updateSideNames();
void MemorySearch(bool tabulate);

#endif
